version: '3'

services:
  furia_kyf_sql_server:
    container_name: furia_kyf_sql_server
    image: mcr.microsoft.com/mssql/server
    environment:
      - MSSQL_USER=${DATABASE_USER}
      - MSSQL_SA_PASSWORD=${DATABASE_PWD}
      - ACCEPT_EULA=Y
      - TZ=America/Sao_Paulo
    ports:
      - "1433:1433"